import type { Metadata } from "next";
import { Kiwi_Maru } from "next/font/google";

import "./globals.css";

const KiwiMaruFont = Kiwi_Maru({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="ja-JP">
      <body className={KiwiMaruFont.className}>
        {children}</body>
    </html>
  );
}
